/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS `pension_fund_members`;

DROP TABLE IF EXISTS `pension_fund`;

DROP TABLE IF EXISTS `employee_emails`;

DROP TABLE IF EXISTS `employee`;

DROP TABLE IF EXISTS `employer`;

CREATE TABLE `employer` (
  `name` VARCHAR(255) NOT NULL PRIMARY KEY)
 ENGINE=InnoDB;

CREATE TABLE `employee` (
  `id` BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `first` TEXT NOT NULL,
  `last` TEXT NOT NULL,
  `employer` VARCHAR(255) NOT NULL
  /*
  CONSTRAINT `employee_employer_fk`
    FOREIGN KEY (`employer`)
    REFERENCES `employer` (`name`)
  */)
 ENGINE=InnoDB;

CREATE TABLE `employee_emails` (
  `object_id` BIGINT UNSIGNED NOT NULL,
  `value` TEXT NOT NULL,
  CONSTRAINT `employee_emails_object_id_fk`
    FOREIGN KEY (`object_id`)
    REFERENCES `employee` (`id`)
    ON DELETE CASCADE)
 ENGINE=InnoDB;

CREATE INDEX `object_id_i`
  ON `employee_emails` (`object_id`);

CREATE TABLE `pension_fund` (
  `name` VARCHAR(255) NOT NULL PRIMARY KEY)
 ENGINE=InnoDB;

CREATE TABLE `pension_fund_members` (
  `object_id` VARCHAR(255) NOT NULL,
  `index` BIGINT UNSIGNED NOT NULL,
  `value` BIGINT UNSIGNED NOT NULL,
  CONSTRAINT `pension_fund_members_object_id_fk`
    FOREIGN KEY (`object_id`)
    REFERENCES `pension_fund` (`name`)
    ON DELETE CASCADE
  /*
  CONSTRAINT `pension_fund_members_value_fk`
    FOREIGN KEY (`value`)
    REFERENCES `employee` (`id`)
  */)
 ENGINE=InnoDB;

CREATE INDEX `object_id_i`
  ON `pension_fund_members` (`object_id`);

CREATE INDEX `index_i`
  ON `pension_fund_members` (`index`);

